Repository univelop/yust_ui, pull requests merged in 2023-12, with the labels that each got.

#106 Dynamic yust select
  lib/src/widgets/yust_select.dart
  lib/src/widgets/yust_select_form.dart
  lib/src/widgets/yust_select_multiple.dart
  pubspec.yaml
Labels: ✅ Approved

#108 allow completion of invalid input
  lib/src/widgets/yust_text_field.dart
Labels: 🔍 Ready for Review

#104 make YustPaginatedListView reversible
  lib/src/widgets/yust_paginated_list_view.dart
Labels: ✅ Approved

#105 Show preview option for image picker
  lib/src/widgets/yust_image_picker.dart
Labels: ✅ Approved

#110 Improve YustSelect
  lib/src/widgets/yust_select.dart
Labels: bug, ✅ Approved

#109 Fix yust image picker delete bug
  lib/src/widgets/yust_image_picker.dart
  lib/src/widgets/yust_input_tile.dart
  lib/src/widgets/yust_select.dart
Labels: 🔍 Ready for Review, ✅ Approved

#101 Allow 5 lines of validator messages in TextFieldDialog
  lib/src/services/yust_alert_service.dart
Labels: ✅ Approved
