Repository univelop/yust_ui, pull requests merged in 2024-02, with the labels that each got.

#114 2520 multilingual YustUi
  lib/src/extensions/string_translate_extension.dart
  lib/src/generated/locale_keys.g.dart
  lib/src/screens/yust_account_edit_screen.dart
  lib/src/screens/yust_account_screen.dart
  lib/src/screens/yust_image_drawing_screen.dart
  lib/src/screens/yust_reset_password_screen.dart
  lib/src/screens/yust_sign_in_screen.dart
  lib/src/screens/yust_sign_up_screen.dart
  lib/src/services/yust_alert_service.dart
  lib/src/util/yust_file_handler.dart
  lib/src/util/yust_file_helpers.dart
  lib/src/widgets/yust_date_picker.dart
  lib/src/widgets/yust_file_picker.dart
  lib/src/widgets/yust_image_picker.dart
  lib/src/widgets/yust_select.dart
  lib/src/widgets/yust_select_form.dart
  lib/src/widgets/yust_select_multiple.dart
  lib/src/widgets/yust_time_picker.dart
  lib/src/yust_ui.dart
  pubspec.yaml
Labels: 🔍 Ready for Review

#116 Change dependency to master
  pubspec.yaml
Labels: ✅ Approved

#117 #2760 Add labelOverflow option
  lib/src/widgets/yust_list_tile.dart
Labels: bug, 🔍 Ready for Review
