Repository univelop/yust_ui, pull requests merged in 2024-06, with the labels that each got.

#138 Add autofillHints to YustTextField
  lib/src/generated/locale_keys.g.dart
  lib/src/widgets/yust_text_field.dart
Labels: 🔍 Ready for Review, ✅ Approved

#139 Refactor number field and time picker
  lib/src/generated/locale_keys.g.dart
  lib/src/widgets/yust_number_field.dart
  lib/src/widgets/yust_text_field.dart
  lib/src/widgets/yust_time_picker.dart
Labels: bug, ✅ Approved

#140 Added labelStyle
  lib/src/widgets/yust_input_tile.dart
  lib/src/widgets/yust_text_field.dart
Labels: ✅ Approved

#125 #2803 - automaticly focusing searchbar in dialogs
  lib/src/widgets/yust_select.dart
  lib/src/widgets/yust_select_form.dart
Labels: ✅ Approved

#143 allow YustNumberField to disable complete on unfocus
  lib/src/widgets/yust_number_field.dart
Labels: 🔍 Ready for Review

#136 Refactor dropzone
  lib/src/util/yust_file_helpers.dart
  lib/src/widgets/yust_dropzone_list_tile.dart
  lib/src/widgets/yust_file_picker.dart
  lib/src/widgets/yust_image_picker.dart
Labels: 🔍 Ready for Review
